Update xml-validation.yml

diff --git a/.github/workflows/xml-validation.yml b/.github/workflows/xml-validation.yml
--- a/.github/workflows/xml-validation.yml
+++ b/.github/workflows/xml-validation.yml
@@ -34,7 +34,6 @@ jobs:
         env:
           CLASSPATH: ".:xerces/xercesImpl.jar:xerces/xml-apis.jar"
         run: |
-          set +e
           error_messages=""
           for file in $(find ./ValidationTest -name "*.xml"); do
             echo "Validating $file"
@@ -43,11 +42,11 @@ jobs:
             if [ $? -ne 0 ]; then
               error_messages="$error_messages\nValidation failed for $file:\n$validation_output\n"
             fi
-
-            if [ -n "$error_messages" ]; then
-              echo -e "Validation completed with errors:\n$error_messages"
-              exit 1
-            else
-              echo "All files validated successfully."
-            fi
           done
+
+          if [ -n "$error_messages" ]; then
+            echo -e "Validation completed with errors:\n$error_messages"
+            exit 1
+          else
+            echo "All files validated successfully."
+          fi
